debug.dump_rom_task(): Added ROM2.BIN for 550D. Moved out of #if CONFIG_DEBUGMSG because of vram.c:(.text+0xf8): undefined reference to `menu_draw_icon' debug.o:(.data+0xfc): undefined reference to `bmp_draw_palette'
--HG--
branch : unified